"""empty message

Revision ID: 55632e3dfe23
Revises: daec15152fbb
Create Date: 2022-11-30 18:52:25.509069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55632e3dfe23'
down_revision = 'daec15152fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mascota_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Mascotas', ['mascota_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mascota_id')

    # ### end Alembic commands ###
